config/routes.rb
Rails.application.routes.draw do

  resources :users

  get 'users/new'

  get 'static_pages/home'

  get 'static_pages/help'

  get 'recipes/index',    to: "recipe#index", as: :index
  get "/recipes/:id",     to: "recipes#show",  as: :recipe
  delete "/recipes/:id",  to: "recipes#delete"

  get "ingredients/index",  to: "ingredients#index", as: :ingredient

  get 'new'  => 'recipes#new'

  get 'signup'  => 'users#new'

  root "recipes#index"

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_and_belongs_to_many :recipes
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  validates :name, :presence => true
  has_and_belongs_to_many :ingredients
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name, presence: true
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def index
    @ingredients = Ingredient.all
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find_by(id: params[:id])
    if @recipe == nil
      redirect_to root_path
    end
  end

  def delete
    recipe = Recipe.find(params[:id])

    recipe.destroy
    redirect_to root_path
  end

  def new
    @recipe = Recipe.new
  end

  def test
    @recipes = Recipe.all
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ingredients/index.html.erb
<% @ingredients.collect do |ingredient| %>
  <%= link_to "#{ingredient.name}", ingredient %>
  <br>
  
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="#">Coffee Express</a>
    by <a href="#">JavaRabbit</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Seattle Coffee Recipes Galore", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "Home",   '/' %></li>
        <li><%= link_to "Help",   '#' %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cooks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!--this render added listing 5.8  -->
  <%= render 'layouts/shim' %>
</head>
<body>
  <!-- <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Seattle Coffee Recipes Galore", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav pull-right">
            <li><%= link_to "Home",   '#' %></li>
            <li><%= link_to "Help",   '#' %></li>
            <li><%= link_to "Log in", '#' %></li>
          </ul>
        </nav>
      </div>
    </header> -->

<%= render 'layouts/header' %>

<div class = "container">
  <%= yield %>
</div>

<%= render 'layouts/footer' %>


</body>
</html>

app/views/recipes/index.html.erb
<h2>Espresso Recipes</h2>

<!--This will list all the recipes  -->
<% @recipes.collect do |recipe| %>
  <%= link_to "#{recipe.name}", recipe %>
  <br>
  <!-- <%= recipe.name %><br> -->
<% end %>
<br>
<%= link_to "Create a new recipe", new_path, class: "btn btn-lg btn-primary" %>

<br><br>

<%= link_to "View all ingredients", ingredient_path, class: "btn btn-lg btn-primary" %>
<br><br>

<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>

app/views/recipes/new.html.erb
Create a new recipe here!

app/views/recipes/show.html.erb
  <tr>
    <td><%= @recipe.name %></td><br>
    Directions: <br>
    <td><%= @recipe.directions %></td><br>
    <td><%= link_to 'Destroy', @recipe, method: :delete %></td>
  </tr>

app/views/recipes/test.html.erb
this isthe test page

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>This is the static pages home :_</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>This will be a signup page for new users.</p>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>

 